# Generated by Django 4.1.7 on 2023-03-02 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 3, 2, 17, 34, 49, 661519, tzinfo=datetime.timezone.utc))),
                ('memo', models.TextField()),
            ],
        ),
    ]
